grafana:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ${clusterIssuer}
    enabled: true
    hosts:
      - ${fqdn}
    tls:
      - hosts:
          - ${fqdn}
        secretName: grafana-tls
  adminPassword: ${adminPassword}

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
