repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: jetpack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

environments:
  default:
    values:
      - values.yaml
    secrets:
      - secrets.enc.yaml

helmDefaults:
  createNamespace: true
  wait: true

releases:
  # Persistent storage CSI driver
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.2.3

  # SSL Certificates
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.6.1
    set:
      - name: installCRDs
        value: true

  # Let's encrypt issuers
  - name: issuers
    namespace: cert-manager
    chart: ./charts/issuers
    needs:
      - cert-manager/cert-manager

  # Monitoring
  - name: prometheus-grafana
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 31.0.0
    values:
      - values/prometheus-grafana.yaml.gotmpl
    needs:
      - cert-manager/issuers
      - longhorn-system/longhorn

  # DDNS updater
  - name: ddclient
    namespace: tools
    chart: ./charts/ddclient
    values:
      - values/ddclient.yaml.gotmpl

  ##################
  ## APPLICATIONS ##
  ##################

  # Home assistant installation
  - name: home-assistant
    namespace: home-assistant
    chart: ./charts/home-assistant
    needs:
      - cert-manager/issuers
      - longhorn-system/longhorn
    values:
      - values/home-assistant.yaml.gotmpl
