apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  secrets.yaml: |-
    dbUrl: postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.hostname }}/{{ .Values.postgresql.database }}
    mqttHost: {{ .Release.Name }}-mosquitto
    mqttUsername: {{ .Values.mosquitto.username }}
    mqttPassword: {{ .Values.mosquitto.password }}
    spotifyClientId: {{ .Values.spotify.clientId }}
    spotifyClientSecret: {{ .Values.spotify.clientSecret }}
    googleProjectId: {{ .Values.google.projectId }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-account
stringData:
  serviceAccount.json: |-
{{ .Values.google.serviceAccount | indent 4 }}
    