apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  # type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      # nodePort: 30123
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mosquitto
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zigbee2mqtt
spec:
  selector:
    app: {{ .Release.Name }}-zigbee2mqtt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080