apiVersion: v2
name: home-assistant
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: 10.16.1
    repository: https://charts.bitnami.com/bitnami
