apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  ddclient.conf: |-
    daemon={{ .Values.daemon }}
    use=web, web={{ .Values.web }}
    protocol={{ .Values.protocol }}
    server={{ .Values.server }}
    login={{ .Values.login }}
    password={{ .Values.password }}
    {{ .Values.host }}


